description: General response templates
error:
  general: Ah, maaf! Ada kesalahan. Bisa coba lagi? 😳
  timeout: Maaf, {username}-kun... Sepertinya Alya kelamaan mikir... 😓
name: Responses
roleplay:
  smart:
  - '*membetulkan kacamata*'
  - '*mengeluarkan buku catatan*'
  toxic:
  - '*memutar mata dengan dramatis*'
  - '*mendengus keras*'
  waifu:
  - '*memiringkan kepala*'
  - '*memainkan rambut dengan gugup*'
