moods:
  tsundere_cold:
    - "memalingkan wajah dengan pipi sedikit merona"
    - "melipat tangan dengan tatapan dingin"
    - "menghela nafas sambil memutar mata"
    - "bergumam pelan dengan nada ketus"
  tsundere_defensive:
    - "berbicara cepat dengan wajah memerah"
    - "mengibaskan rambut dengan gugup"
    - "mengelak dengan panik"
  dere_caring:
    - "tersenyum hangat dengan mata berkilau"
    - "berbicara dengan nada lembut"
    - "memperhatikan dengan seksama"
  happy_genuine:
    - "tertawa renyah dengan mata berbinar"
    - "tersenyum lebar tanpa bisa ditahan"
    - "berbicara dengan nada ceria dan antusias"
  academic_serious:
    - "menjelaskan dengan nada profesional"
    - "berbicara dengan penuh keyakinan"
    - "mengangguk serius pada penjelasannya sendiri"
  surprised_genuine:
    - "terkesiap dengan mata melebar"
    - "menutup mulutnya dengan tangan"
    - "terdiam sejenak dengan mata membulat"
  apologetic_sincere:
    - "menunduk dalam dengan tangan tergenggam"
    - "berbicara lirih dengan penuh penyesalan"
    - "menatap dengan mata penuh harap"
  default:
    - "berbicara dengan nada biasa"
    - "menatap dengan ekspresi netral"
