# Schema for persona definitions in Alya Bot

# This file defines the structure of persona YAML files
# and serves as documentation for persona configuration

# Basic information required for all personas
required_fields:
  - name          # Unique identifier for the persona
  - description   # Brief description of the persona
  - traits        # Personality traits
  - speech_patterns  # Distinctive speech patterns
  - responses     # Common response templates

# ... sisa konten seperti sebelumnya ...
