# Template for creating new personas

# Basic information
name: "new_persona"  # Change to unique identifier
description: "Description of this persona"

# Core personality traits
traits:
  dominant:
    - "trait1"
    - "trait2"
    - "trait3"
  
# ... sisa konten seperti sebelumnya ...
